### ISSUE TITLE
do the thing

### ISSUE THREAD

**Issue by Wizek** [ancarda/rosenbot#1]

**Comment by ancarda** [comment]
From IRC:

>_FYI, it still does the "don't bug people I already spoke to" thing, I can remove that (actually, could you raise an issue on GitHub so I can remember to do this?)_

Well, I guess you technically did raise **an issue** on GitHub...

------

For my future self: rosenbot adds people to an ignore list so they are only told on JOIN once that they should join ##nvc. It's been suggested that this may not be such a good idea as someone returning many days or weeks later may not remember #nvc is abandoned, but rosenbot never forgets anything.

@Wizek: Are you thinking this whole feature should be removed, or would you like it to perhaps remember you for some time, e.g. 12 hours?

**Comment by Wizek** [comment]
I think it would be simplest to just remove/comment it out for now, and later you may enable it with more sophistication. Also, I think the timeout I would choose is lower, e.g. 5-15 minutes just for repeated reconnects, but even still I am not sure this feature is worth the added complexity it brings.

**Comment by Wizek** [comment]
It's quite simple
